# Generated by Django 4.0.1 on 2022-02-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], default='male', max_length=6)),
                ('dob', models.DateField()),
                ('registrationDate', models.DateField()),
                ('uidOrAadhaar', models.CharField(blank=True, max_length=12)),
                ('careGiversName', models.CharField(blank=True, max_length=200)),
                ('reletionship', models.CharField(blank=True, choices=[('aunt', 'AUNT'), ('brother', 'BROTHER'), ('father', 'FATHER'), ('grandfather', 'GRANDFATHER'), ('grandmother', 'GRANDMOTHER'), ('guardian', 'GUARDIAN'), ('husband', 'HUSBAND'), ('mother', 'MOTHER'), ('other', 'OTHER'), ('sister', 'SISTER'), ('uncle', 'UNCLE'), ('wife', 'WIFE')], default='other', max_length=200)),
                ('beneficiaryType', models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE'), ('migrated', 'MIGRATED'), ('deceased', 'DECEASED')], default='active', max_length=200)),
                ('statusOfBeneficiary', models.CharField(choices=[('red', 'RED'), ('yellow', 'YELLOW'), ('green', 'GREEN')], default='red', max_length=200)),
            ],
        ),
    ]
