# Generated by Django 4.0.1 on 2022-02-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_beneficiary_address_alter_beneficiary_caregiversname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='addressType',
            field=models.CharField(blank=True, choices=[('residence', 'RESIDENCE'), ('office', 'OFFICE'), ('permanent', 'PERMANENT'), ('present', 'PRESENT'), ('communication', 'COMMUNICATION'), ('native', 'NATIVE'), ('relative', 'RELATIVE'), ('temporary', 'TEMPORARY')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='city',
            field=models.CharField(default='darrang', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='district',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='pinCode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
