# Generated by Django 4.0.1 on 2022-02-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_beneficiary_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('purpose_of_visit_for_old_paitent', models.CharField(blank=True, choices=[('', 'PAITENT FOLLOW UP'), ('', 'PAITENT COUNSELLING'), ('', 'CARE GIVER COUNSELLING'), ('', 'AWARENESS MEETING'), ('', 'LIVILIHOOD REHABILITATION'), ('', 'MONITORING'), ('', 'MEETING WITH VILLAGE LEVEL COMMITTEE'), ('', 'OTHER')], max_length=200, null=True)),
                ('is_new_patient', models.BooleanField(default=False)),
                ('action_planned_for_new_patient', models.CharField(blank=True, max_length=200, null=True)),
                ('symptoms_of_new_patient', models.TextField(blank=True, null=True)),
                ('note_on_new_patient', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='purposeOfVisit',
            field=models.CharField(blank=True, choices=[('', 'PAITENT FOLLOW UP'), ('', 'PAITENT COUNSELLING'), ('', 'CARE GIVER COUNSELLING'), ('', 'AWARENESS MEETING'), ('', 'LIVILIHOOD REHABILITATION'), ('', 'MONITORING'), ('', 'MEETING WITH VILLAGE LEVEL COMMITTEE'), ('', 'OTHER')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_visited', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_of_visit', models.DateField()),
                ('date', models.DateField(auto_now=True)),
                ('name_of_new_patients', models.ManyToManyField(blank=True, null=True, to='home.Patient')),
                ('name_of_old_patients', models.ManyToManyField(blank=True, null=True, related_name='old_patients', to='home.Patient')),
            ],
        ),
    ]
