# Generated by Django 4.0.1 on 2022-02-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='careGiversName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='reletionship',
            field=models.CharField(blank=True, choices=[('aunt', 'AUNT'), ('brother', 'BROTHER'), ('father', 'FATHER'), ('grandfather', 'GRANDFATHER'), ('grandmother', 'GRANDMOTHER'), ('guardian', 'GUARDIAN'), ('husband', 'HUSBAND'), ('mother', 'MOTHER'), ('other', 'OTHER'), ('sister', 'SISTER'), ('uncle', 'UNCLE'), ('wife', 'WIFE')], default='other', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='uidOrAadhaar',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
