# Generated by Django 4.0.1 on 2022-02-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_beneficiary_purposeofvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='educationHistory',
            field=models.CharField(choices=[('illiterate', 'ILLITERATE'), ('upto class v', 'UPTO CLASS V'), ('upto class viii', 'UPTO CLASS VIII'), ('under matric', 'UNDER MATRIC'), ('matriculation', 'MATRICULATION'), ('degree', 'DEGREE'), ('pg and above', 'PG AND ABOVE')], default='illiterate', max_length=200),
            preserve_default=False,
        ),
    ]
