# Generated by Django 4.0.1 on 2022-02-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_beneficiary_educationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='familyMonthlyIncome',
            field=models.CharField(blank=True, choices=[('less than rs.2500', 'LESS THAN RS.2500'), ('rs.2500-rs.5000', 'RS.2500-RS.5000'), ('rs.5000-rs.7000', 'RS.5000-RS.7000'), ('rs.7000-rs.10000', 'RS.7000-RS.10000'), ('rs.10000-rs.15000', 'RS.10000-RS.15000'), ('rs.15000-rs.20000', 'RS.15000-RS.20000'), ('more than rs.20000', 'MORE THAN RS.20000')], max_length=200, null=True),
        ),
    ]
