# Generated by Django 4.0.1 on 2022-02-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_beneficiary_martialstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='durationOfIllness',
            field=models.CharField(blank=True, choices=[('sudden(few days or week)', 'SUDDEN(FEW DAYS OR WEEK)'), ('acute(few weeks to a month)', 'ACUTE(FEW WEEKS TO A MONTH)'), ('indidious(over many months)', 'INDIODIOUS(OVER MANY MONTHS)'), ('not applicable(eg epilepsy/mr)', 'NOT APPLICABLE(EG EPILEPSY/MR)'), ('unclear', 'UNCLEAR')], max_length=200, null=True),
        ),
    ]
