# Generated by Django 4.0.1 on 2022-02-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_beneficiary_pastpyschiatricillness'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='family_history_of_MI_present_or_absent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='gp',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='if_present_schizophrenia_or_mania_or_depression',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='village',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
