# Generated by Django 4.0.1 on 2022-02-04 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_beneficiary_family_history_of_mi_present_or_absent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiary',
            old_name='martialStatus',
            new_name='maritialStatus',
        ),
    ]
