# Generated by Django 4.0.1 on 2022-02-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_martialstatus_beneficiary_maritialstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
