# Generated by Django 4.0.1 on 2022-02-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_beneficiary_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop/images/'),
        ),
    ]
