# Generated by Django 4.0.1 on 2022-03-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_patient_alter_beneficiary_purposeofvisit_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='designation',
            field=models.CharField(choices=[('', 'Village committe member'), ('', 'ASHA'), ('', 'Anganwadi'), ('', 'ANM'), ('', 'Neighbours'), ('', 'Village shopkeeper'), ('', 'Other')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='diagnosedBy',
            field=models.CharField(choices=[('', 'Dr.J K Nath'), ('', 'Dr.P Kalita'), ('', 'Dr.Iftikar Hussain'), ('', 'Dr.Sujata Borkakoty')], default='', max_length=200),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='informedBy',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='symptomsAsInformed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
