# Generated by Django 4.0.1 on 2022-03-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_beneficiary_designation_beneficiary_diagnosedby_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(max_length=3)),
                ('sex', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], max_length=200)),
                ('village', models.CharField(max_length=200)),
                ('diagonisis', models.CharField(choices=[('bipolar', 'BIPOLAR'), ('schizophrenia', 'SCHIZOPHRENIA'), ('depression', 'DEPRESSION'), ('mania', 'MANIA'), ('anxiety disorders', 'ANXIETY DISORDERS'), ('panic disorder', 'PANIC DISORDER'), ('stress-related disorders', 'STRESS-RELATED DISORDERS'), ('dissociative disorders', 'DISSOCIATIVE DISORDERS'), ('dissociative amnesia', 'DISSOCIATIVE AMNESIA'), ('somatic symptom disorder', 'SOMATIC SYMPTOM DISORDER'), ('insomnia disorder', 'INSOMNIA DISORDER'), ('substance-related disorders', 'SUBSTANCE-RELATED DISORDERS'), ('obsessive-compulsive disorders (ocd)', 'OBSESSIVE-COMPULSIVE DISORDERS (OCD)'), ('personality disorders', 'PERSONALITY DISORDERS'), ('paranoid personality disorder', 'PARANOID PERSONALITY DISORDER'), ('other', 'OTHER')], max_length=200)),
                ('identification_date', models.DateField()),
                ('name_of_medicine_taking', models.CharField(max_length=200)),
                ('screening_camp_date', models.DateField()),
                ('name_of_psychiatrist', models.CharField(max_length=200)),
                ('advice_by_psychiatrist', models.TextField()),
                ('counselling_by', models.CharField(max_length=200)),
                ('color_suggested_by_psychiatrist', models.CharField(choices=[('red', 'RED'), ('yellow', 'YELLOW'), ('green', 'GREEN')], max_length=200)),
                ('next_review_date', models.DateField()),
                ('submitted_by', models.CharField(max_length=200)),
                ('upload_prescription', models.FileField(blank=True, null=True, upload_to='home/files/')),
            ],
            options={
                'db_table': 'Patient Camp',
            },
        ),
        migrations.AlterModelOptions(
            name='beneficiary',
            options={'verbose_name_plural': 'Beneficiaries'},
        ),
    ]
