# Generated by Django 4.0.1 on 2022-03-20 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_camp_alter_beneficiary_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camp',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(1)]),
        ),
    ]
