# Generated by Django 4.0.1 on 2022-03-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_camp_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='note_on_new_patient',
            new_name='note_on_old_patient',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='familyMonthlyIncome',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='occupation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='idendified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='familyMonthlyIncome',
            field=models.CharField(blank=True, choices=[('less than rs.2500', 'LESS THAN RS.2500'), ('rs.2500-rs.5000', 'RS.2500-RS.5000'), ('rs.5000-rs.7000', 'RS.5000-RS.7000'), ('rs.7000-rs.10000', 'RS.7000-RS.10000'), ('rs.10000-rs.15000', 'RS.10000-RS.15000'), ('rs.15000-rs.20000', 'RS.15000-RS.20000'), ('more than rs.20000', 'MORE THAN RS.20000')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='no_of_family_members',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='no_of_siblings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='purposeOfVisit',
            field=models.CharField(blank=True, choices=[('', 'PATIENT FOLLOW UP'), ('', 'PATIENT COUNSELLING'), ('', 'CARE GIVER COUNSELLING'), ('', 'AWARENESS MEETING'), ('', 'LIVILIHOOD REHABILITATION'), ('', 'MONITORING'), ('', 'MEETING WITH VILLAGE LEVEL COMMITTEE'), ('', 'OTHER')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='purpose_of_visit_for_old_paitent',
            field=models.CharField(blank=True, choices=[('', 'PATIENT FOLLOW UP'), ('', 'PATIENT COUNSELLING'), ('', 'CARE GIVER COUNSELLING'), ('', 'AWARENESS MEETING'), ('', 'LIVILIHOOD REHABILITATION'), ('', 'MONITORING'), ('', 'MEETING WITH VILLAGE LEVEL COMMITTEE'), ('', 'OTHER')], max_length=200, null=True),
        ),
    ]
