# Generated by Django 4.0.1 on 2022-03-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_note_on_new_patient_patient_note_on_old_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='purposeOfVisit',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='birth',
            field=models.CharField(blank=True, choices=[('', 'Normal'), ('', 'Abnormal'), ('', 'Other')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='skill',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('', 'A+ve'), ('', 'B+ve'), ('', 'O+ve'), ('', 'AB+ve'), ('', 'A-ve'), ('', 'B-ve'), ('', 'O-ve'), ('', 'AB-ve')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='identification_mark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='diagnosedBy',
            field=models.CharField(choices=[('', 'Dr.J K Nath'), ('', 'Dr.P Kalita'), ('', 'Dr.Iftikar Hussain'), ('', 'Dr.Sujata Borkakoty'), ('', 'Others')], default='', max_length=200),
        ),
    ]
