# Generated by Django 4.0.1 on 2022-03-26 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_beneficiary_purposeofvisit_beneficiary_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], max_length=200)),
                ('fatherName', models.CharField(max_length=200)),
                ('motherName', models.CharField(max_length=200)),
                ('careGiver', models.CharField(max_length=200)),
                ('relationship', models.CharField(choices=[('aunt', 'AUNT'), ('brother', 'BROTHER'), ('father', 'FATHER'), ('grandfather', 'GRANDFATHER'), ('grandmother', 'GRANDMOTHER'), ('guardian', 'GUARDIAN'), ('husband', 'HUSBAND'), ('mother', 'MOTHER'), ('other', 'OTHER'), ('sister', 'SISTER'), ('uncle', 'UNCLE'), ('wife', 'WIFE')], max_length=200)),
                ('address', models.TextField()),
                ('village', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('designation', models.CharField(choices=[('', 'Village committe member'), ('', 'ASHA'), ('', 'Anganwadi'), ('', 'ANM'), ('', 'Neighbours'), ('', 'Village shopkeeper'), ('', 'Other')], max_length=200)),
                ('disability', models.CharField(choices=[('', 'Locamator'), ('', 'Low vision'), ('', 'Blindness'), ('', 'Hearing impairment'), ('', 'Mental retardation'), ('', 'Mental illness')], max_length=200)),
                ('visitedBy', models.CharField(max_length=200)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.beneficiary')),
            ],
        ),
    ]
