# Generated by Django 4.0.1 on 2022-03-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_screeningcamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='birth',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Abnormal', 'Abnormal'), ('Other', 'Other')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='designation',
            field=models.CharField(choices=[('Village committe member', 'Village committe member'), ('ASHA', 'ASHA'), ('Anganwadi', 'Anganwadi'), ('ANM', 'ANM'), ('Neighbours', 'Neighbours'), ('Village shopkeeper', 'Village shopkeeper'), ('Other', 'Other')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='diagnosedBy',
            field=models.CharField(choices=[('Dr.J K Nath', 'Dr.J K Nath'), ('Dr.P Kalita', 'Dr.P Kalita'), ('Dr.Iftikar Hussain', 'Dr.Iftikar Hussain'), ('Dr.Sujata Borkakoty', 'Dr.Sujata Borkakoty'), ('Others', 'Others')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='purpose_of_visit_for_old_paitent',
            field=models.CharField(blank=True, choices=[('PATIENT FOLLOW UP', 'PATIENT FOLLOW UP'), ('PATIENT COUNSELLING', 'PATIENT COUNSELLING'), ('CARE GIVER COUNSELLING', 'CARE GIVER COUNSELLING'), ('AWARENESS MEETING', 'AWARENESS MEETING'), ('LIVILIHOOD REHABILITATION', 'LIVILIHOOD REHABILITATION'), ('MONITORING', 'MONITORING'), ('MEETING WITH VILLAGE LEVEL COMMITTEE', 'MEETING WITH VILLAGE LEVEL COMMITTEE'), ('OTHER', 'OTHER')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+ve', 'A+ve'), ('B+ve', 'B+ve'), ('O+ve', 'O+ve'), ('AB+ve', 'AB+ve'), ('A-ve', 'A-ve'), ('B-ve', 'B-ve'), ('O-ve', 'O-ve'), ('AB-ve', 'AB-ve')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='screeningcamp',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='screeningcamp',
            name='careGiver',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='screeningcamp',
            name='designation',
            field=models.CharField(blank=True, choices=[('Village committe member', 'Village committe member'), ('ASHA', 'ASHA'), ('Anganwadi', 'Anganwadi'), ('ANM', 'ANM'), ('Neighbours', 'Neighbours'), ('Village shopkeeper', 'Village shopkeeper'), ('Other', 'Other')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='screeningcamp',
            name='disability',
            field=models.CharField(blank=True, choices=[('Locamator', 'Locamator'), ('Low vision', 'Low vision'), ('Blindness', 'Blindness'), ('Hearing impairment', 'Hearing impairment'), ('Mental retardation', 'Mental retardation'), ('Mental illness', 'Mental illness')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='screeningcamp',
            name='dob',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='screeningcamp',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], max_length=200),
        ),
        migrations.AlterField(
            model_name='screeningcamp',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='screeningcamp',
            name='relationship',
            field=models.CharField(blank=True, choices=[('aunt', 'AUNT'), ('brother', 'BROTHER'), ('father', 'FATHER'), ('grandfather', 'GRANDFATHER'), ('grandmother', 'GRANDMOTHER'), ('guardian', 'GUARDIAN'), ('husband', 'HUSBAND'), ('mother', 'MOTHER'), ('other', 'OTHER'), ('sister', 'SISTER'), ('uncle', 'UNCLE'), ('wife', 'WIFE')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='screeningcamp',
            name='village',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='screeningcamp',
            name='visitedBy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
