# Generated by Django 4.0.1 on 2022-03-27 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_beneficiary_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screeningcamp',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.beneficiary'),
        ),
    ]
