# Generated by Django 4.0.1 on 2022-03-28 00:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_screeningcamp_blood_pressure_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiary',
            old_name='family_history_of_MI_present_or_absent',
            new_name='if_family_history_of_MI_present',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='address',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='city',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='gp',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='uidOrAadhaar',
        ),
        migrations.RemoveField(
            model_name='screeningcamp',
            name='address',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='id_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='id_type',
            field=models.CharField(blank=True, choices=[('Aadhar', 'Aadhar'), ('Voter ID', 'Voter ID'), ('DL', 'DL'), ('Passport', 'Passport'), ('Pan Card', 'Pan Card'), ('Ration Card', 'Ration Card'), ('other', 'other')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='screeningcamp',
            name='birth',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('abnormal', 'Abnormal'), ('other', 'Other')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='screeningcamp',
            name='color_suggested_by_psychiatrist',
            field=models.CharField(blank=True, choices=[('red', 'RED'), ('yellow', 'YELLOW'), ('green', 'GREEN')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='screeningcamp',
            name='diagnosed_by',
            field=models.CharField(blank=True, choices=[('Dr.J K Nath', 'Dr.J K Nath'), ('Dr.P Kalita', 'Dr.P Kalita'), ('Dr.Iftikar Hussain', 'Dr.Iftikar Hussain'), ('Dr.Sujata Borkakoty', 'Dr.Sujata Borkakoty'), ('Others', 'Others')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='screeningcamp',
            name='diagnosis',
            field=models.CharField(blank=True, choices=[('bipolar', 'BIPOLAR'), ('schizophrenia', 'SCHIZOPHRENIA'), ('depression', 'DEPRESSION'), ('mania', 'MANIA'), ('anxiety disorders', 'ANXIETY DISORDERS'), ('panic disorder', 'PANIC DISORDER'), ('stress-related disorders', 'STRESS-RELATED DISORDERS'), ('dissociative disorders', 'DISSOCIATIVE DISORDERS'), ('dissociative amnesia', 'DISSOCIATIVE AMNESIA'), ('somatic symptom disorder', 'SOMATIC SYMPTOM DISORDER'), ('insomnia disorder', 'INSOMNIA DISORDER'), ('substance-related disorders', 'SUBSTANCE-RELATED DISORDERS'), ('obsessive-compulsive disorders (ocd)', 'OBSESSIVE-COMPULSIVE DISORDERS (OCD)'), ('personality disorders', 'PERSONALITY DISORDERS'), ('paranoid personality disorder', 'PARANOID PERSONALITY DISORDER'), ('other', 'OTHER')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='screeningcamp',
            name='duration_of_illness',
            field=models.CharField(blank=True, choices=[('sudden(few days or week)', 'SUDDEN(FEW DAYS OR WEEK)'), ('acute(few weeks to a month)', 'ACUTE(FEW WEEKS TO A MONTH)'), ('indidious(over many months)', 'INDIODIOUS(OVER MANY MONTHS)'), ('not applicable(eg epilepsy/mr)', 'NOT APPLICABLE(EG EPILEPSY/MR)'), ('unclear', 'UNCLEAR')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='screeningcamp',
            name='education_history',
            field=models.CharField(blank=True, choices=[('illiterate', 'ILLITERATE'), ('upto class v', 'UPTO CLASS V'), ('upto class viii', 'UPTO CLASS VIII'), ('under matric', 'UNDER MATRIC'), ('matriculation', 'MATRICULATION'), ('degree', 'DEGREE'), ('pg and above', 'PG AND ABOVE')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='screeningcamp',
            name='identified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='screeningcamp',
            name='maritial_status',
            field=models.CharField(blank=True, choices=[('unmarried', 'UNMARRIED'), ('married', 'MARRIED'), ('separated', 'SEPARATED'), ('widow', 'WIDOW'), ('remarried', 'REMARRIED')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='screeningcamp',
            name='name_of_medicine_taking',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='screeningcamp',
            name='name_of_psychiatrist',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='screeningcamp',
            name='next_review_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screeningcamp',
            name='occupation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='screeningcamp',
            name='past_pyschiatric_illness',
            field=models.CharField(blank=True, choices=[('absent', 'ABSENT'), ('present', 'PRESENT'), ('unclear', 'UNCLEAR')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='screeningcamp',
            name='skill',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='screeningcamp',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='screeningcamp',
            name='fatherName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='screeningcamp',
            name='motherName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
