# Generated by Django 4.0.1 on 2022-03-28 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_rename_family_history_of_mi_present_or_absent_beneficiary_if_family_history_of_mi_present_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiary',
            old_name='addressType',
            new_name='address_type',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='beneficiaryType',
            new_name='beneficiary_type',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='careGiversName',
            new_name='care_givers_name',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='diagnosedBy',
            new_name='diagnosed_by',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='durationOfIllness',
            new_name='duration_of_illness',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='educationHistory',
            new_name='education_history',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='informedBy',
            new_name='informed_by',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='maritialStatus',
            new_name='maritial_status',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='pastPyschiatricIllness',
            new_name='past_pyschiatric_illness',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='pinCode',
            new_name='pin_code',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='registrationDate',
            new_name='registration_date',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='reletionship',
            new_name='relationship',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='statusOfBeneficiary',
            new_name='status_of_beneficiary',
        ),
        migrations.RenameField(
            model_name='beneficiary',
            old_name='symptomsAsInformed',
            new_name='symptoms_as_informed',
        ),
    ]
