# Generated by Django 4.0.1 on 2022-03-28 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_rename_caregiver_screeningcamp_care_giver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='if_present_schizophrenia_or_mania_or_depression',
        ),
    ]
