# Generated by Django 4.0.1 on 2022-03-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_screeningcamp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='report',
            name='date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='date_of_visit',
        ),
        migrations.RemoveField(
            model_name='report',
            name='familyMonthlyIncome',
        ),
        migrations.RemoveField(
            model_name='report',
            name='height',
        ),
        migrations.RemoveField(
            model_name='report',
            name='identification_mark',
        ),
        migrations.RemoveField(
            model_name='report',
            name='no_of_family_members',
        ),
        migrations.RemoveField(
            model_name='report',
            name='no_of_siblings',
        ),
        migrations.RemoveField(
            model_name='report',
            name='place_visited',
        ),
        migrations.RemoveField(
            model_name='report',
            name='weight',
        ),
        migrations.AddField(
            model_name='report',
            name='purpose_of_visit',
            field=models.CharField(blank=True, choices=[('PATIENT FOLLOW UP', 'PATIENT FOLLOW UP'), ('PATIENT COUNSELLING', 'PATIENT COUNSELLING'), ('CARE GIVER COUNSELLING', 'CARE GIVER COUNSELLING'), ('AWARENESS MEETING', 'AWARENESS MEETING'), ('LIVILIHOOD REHABILITATION', 'LIVILIHOOD REHABILITATION'), ('MONITORING', 'MONITORING'), ('MEETING WITH VILLAGE LEVEL COMMITTEE', 'MEETING WITH VILLAGE LEVEL COMMITTEE'), ('OTHER', 'OTHER')], max_length=200, null=True),
        ),
    ]
