# Generated by Django 4.0.1 on 2022-03-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_remove_report_blood_group_remove_report_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='diagnosed_by',
            field=models.CharField(choices=[('Md.Psychiatry.Dr.J K Nath', 'Md.Psychiatry.Dr.J K Nath'), ('Md.Psychiatry.Dr.P Kalita', 'Md.Psychiatry.Dr.P Kalita'), ('Md.Psychiatry.Dr.Iftikar Hussain', 'Md.Psychiatry.Dr.Iftikar Hussain'), ('Md.Psychiatry.Dr.Sujata Borkakoty', 'Md.Psychiatry.Dr.Sujata Borkakoty'), ('Others', 'Others')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='screeningcamp',
            name='diagnosed_by',
            field=models.CharField(blank=True, choices=[('Md.Psychiatry.Dr.J K Nath', 'Md.Psychiatry.Dr.J K Nath'), ('Md.Psychiatry.Dr.P Kalita', 'Md.Psychiatry.Dr.P Kalita'), ('Md.Psychiatry.Dr.Iftikar Hussain', 'Md.Psychiatry.Dr.Iftikar Hussain'), ('Md.Psychiatry.Dr.Sujata Borkakoty', 'Md.Psychiatry.Dr.Sujata Borkakoty'), ('Others', 'Others')], max_length=200, null=True),
        ),
    ]
